name: Deploy to invest.dolinsky.ch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload website via SFTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          local_path: './*'
          remote_path: ${{ secrets.SSH_REMOTE_PATH }}
          sftp_only: true